# https://www.scylladb.com/wp-content/uploads/scylla-opensource-4.png

version: '3.9'

x-omnistrate-service-plan:
  name: 'ScyllaDB Dedicated w/ NVMe'
  tenancyType: 'OMNISTRATE_DEDICATED_TENANCY'
  deployment:
    hostedDeployment:
      AwsAccountId: '<>'
      AwsBootstrapRoleAccountArn: 'arn:aws:iam::<>:role/omnistrate-bootstrap-role'

x-omnistrate-integrations:
 - omnistrateLogging
 - omnistrateMetrics

services:
  scylla-node:
    image: scylladb/scylla:6.1.5
    command: --seeds "{{ $sys.compute.nodes[*].name }}" --overprovisioned 0 --experimental 0 --developer-mode 0 --io-setup 0 --smp "{{ $sys.compute.node.cores }}" --reserve-memory "4096M" --io-properties-file /etc/scylla.d/io_properties.yaml
    privileged: true
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: false
        export: true
        defaultValue: "i4i.2xlarge"
      - key: username
        description: Superuser username
        name: Superuser Username
        type: String
        modifiable: false
        required: true
        export: true
      - key: saltedPassword
        description: Superuser salted password as processed by mkpassword or similar
        name: Superuser Salted Password
        type: Password
        modifiable: false
        required: true
        export: true
    x-omnistrate-compute:
      replicaCount: 3
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-capabilities:
      enableMultiZone: true
      backupConfiguration:
        backupRetentionInDays: 30
        backupPeriodInHours: 24
    volumes:
      - ./scylla-node-conf-nvme:/etc/scylla
      - ./scylla-server.conf:/etc/supervisord.conf.d/scylla-server.conf
      - ./scylla.d-nvme:/etc/scylla.d
    x-omnistrate-actionhooks:
      # image with netcat
      - image: alpine:3.21.3
        scope: NODE
        type: HEALTH_CHECK
        commandTemplate: |
          nc -z -v -w 5 {{ $sys.compute.node.name }} 9042
          nc -z -v -w 5 {{ $sys.compute.node.name }} 10000
      - image: busybox:1.37
        scope: NODE
        type: INIT
        command:
        - /bin/sh
        - -c
        commandTemplate: |
          # Set the AIO max number of events
          sysctl -w fs.aio-max-nr='{{ $func.mult($sys.compute.node.cores, 51026) }}'
          # Init commitlog directory
          mkdir -p /cache/commitlog
    ports:
      - "9042:9042"  # CQL